### ISSUE TITLE
Usage questions on using your model for applied field research

### ISSUE THREAD

**Issue by asheetal** [csebuetnlp/xl-sum#10]
I am trying to use this model for applied social science studies. Social science research has its own requirements. One of the requirement is that the language cannot be translated before analyzed. But to publish in a paper, the output must be in English. So I have two usage questions

1. My input paragraph is in Hindi, I want the summarizatoin output to be in English. Is this possible?

2. My input is about a chapter length, Will the model be able to summarize a speech, maybe 40,000 words?

**Comment by Tahmid04** [comment]
Hi, thanks for considering our model for your research. We are happy to answer your questions:

1. XL-Sum can only perform in-language summarization, i.e., the source article and the target summary will have the same language. The task you are suggesting is called cross-lingual summarization; you might want to check our work on [CrossSum](https://github.com/csebuetnlp/CrossSum) for cross-lingual summarization.

2. Our models can only support inputs up to 512 tokens, which is roughly around 400 words. You may split your input into paragraphs of smaller lengths, summarize them individually, and aggregate those summaries later.

**Comment by asheetal** [comment]
Thanks for your quick response. @Tahmid04 

Looks like the crosssum model would be a great fit for summarizing field work. Rarely ever field studies are in English. 

So again need to clarify few things

- Can the CrossSum model take input that is mix of English+Hindi and summarize in pure English? The github example output in CrossSum appears in mix of Bangla+English.

- I have a problem with chunking. Often in speeches, people repeat themselves. This is not a problem in written text. Written text is always edited to avoid repetition of topics. But when people give speeches, they often repeat same stories again and again. So chunking has a problem that it the summary will appear gibberish. Do you have any recommendations for it?

**Comment by Tahmid04** [comment]
- The example on the GitHub readme is of a article in Japanese being summarized in Bengali. Both are translated into English for better understanding. The model is not trained on code-mixed texts, but should be able to handle them to some extent. We recommend further fine-tuning the model for better domain adaptation.
- Summarization models are inherently trained to  filter repetitive contents. Note that our group works explicitly on text-based models. So, problems pertinent to other data modalities may not transfer to our use cases.

**Comment by asheetal** [comment]
Thanks.

Finetuning models is beyond the capability of social science researchers. Applied researchers just use models built by computer scientists. I will manually cross-check if the summary was indeed correct. 

I will have to think how to summarize large text with repeating themes. So this problem still seems a bottleneck for field research.

**Comment by Tahmid04** [comment]
Thanks for your consideration; please use [this model](https://huggingface.co/csebuetnlp/mT5_m2m_crossSum_enhanced) if you decide to use CrossSum for your work, it is the most performant of all CrossSum models.
