### ISSUE TITLE
How to use the ```multilingual_rouge_scoring``` correctly in multiple languages

### ISSUE THREAD

**Issue by wenlai-lavine** [csebuetnlp/xl-sum#15]
Hi, I am computing the multilingual rouge score now, but I found it is hard to repro the scores in the Table of ```README.md```.
+ I am using ```calculate_rouge()``` in ```seq2seq/utils.py``` to compute the rouge score.
+ Here is some examples:
```
# here is the chinese example:
# I use:
rouge_score_dict = calculate_rouge(
        pred_lns=pred_list,
        tgt_lns=ref_list,
        use_stemmer=False,
        rouge_keys=["rouge1", "rouge2", "rougeL", "rougeLsum"],
        return_precision_and_recall=False,
        bootstrap_aggregation=True,
        newline_sep=True,
        rouge_lang='chinese'
    )
# return: {'rouge1': 7.7625, 'rouge2': 4.6715, 'rougeL': 6.2677, 'rougeLsum': 1.8609}
# scores in README table: {'rouge1': 39.4071, 'rouge2':  17.7913, 'rougeL':  33.406}
```
```
# here is the bengali example:
# I use:
rouge_score_dict = calculate_rouge(
        pred_lns=pred_list,
        tgt_lns=ref_list,
        use_stemmer=True,
        rouge_keys=["rouge1", "rouge2", "rougeL", "rougeLsum"],
        return_precision_and_recall=False,
        bootstrap_aggregation=True,
        newline_sep=True,
        rouge_lang='bengali'
    )
# return: {'rouge1': 7.759, 'rouge2': 4.6689, 'rougeL': 6.2702, 'rougeLsum': 1.8614}
# scores in README table: {'rouge1': 29.5653, 'rouge2':  12.1095, 'rougeL':   25.1315}
```
I use the same prediction files as in ```README``` table download at [this link](https://docs.google.com/uc?export=download&id=16OaTryW-QCaYevQ9Gtbr7aKhCJKBDEAr). The score is README differs greatly from my running results. Do I miss something? Can anybody help me to clarify this? Thanks!

**Comment by abhik1505040** [comment]
Hi @lavine-lmu, thanks for reaching out. It's tough to directly point out a problem without the exact script and environment you are using. However, I quickly ran a [Colab test](https://colab.research.google.com/drive/1p3QPQ95EkB9qDlBFZZNgsRU1J7fBUEhS?usp=sharing), and everything seems to be in order. 

Please have a look at the shared notebook and let me know if you have any questions.

**Comment by wenlai-lavine** [comment]
> Hi @lavine-lmu, thanks for reaching out. It's tough to directly point out a problem without the exact script and environment you are using. However, I quickly ran a [Colab test](https://colab.research.google.com/drive/1p3QPQ95EkB9qDlBFZZNgsRU1J7fBUEhS?usp=sharing), and everything seems to be in order.
> 
> Please have a look at the shared notebook and let me know if you have any questions.

Sorry, it's my fault. I mistakenly extracted the "text", not the "summary" column from the xl-sum testset. Thanks for the quickly reply.
