### ISSUE TITLE
How to use rouge scorer client correctly

### ISSUE THREAD

**Issue by 18445864529** [csebuetnlp/xl-sum#6]
I followed the readme under `multilingual_rouge_scoring/`and setup successfully but then, 
when I used `python -m rouge.rouge --args` I got 

```
Error while finding module specification for 'rouge.rouge' (ModuleNotFoundError: __path__ attribute not found on 'rouge' while trying to find 'rouge.rouge')
```

when I used `python rouge.py --args` I got 
``` 
File "/net/papilio/storage2/bowenz/tools/xl-sum/multilingual_rouge_scoring/rouge.py", line 71, in main
    scorer = rouge_scorer.RougeScorer(FLAGS.rouge_types, FLAGS.use_stemmer, lang=FLAGS.lang)
TypeError: __init__() takes 2 positional arguments but 3 were given
```

and when I used `rouge --args` I got 

```
rougeval.sh: 1: rouge: not found
```

Any help? thanks.

**Comment by abhik1505040** [comment]
Hi, thank you for pointing out the CLI bug. We've updated the repo accordingly. Try the following steps now:
- Pull the latest version of the repo.
- Reinstall the package with `pip3 install --upgrade multilingual_rouge_scoring/`
- Use the CLI script via `python -m rouge_score.rouge --args`

This should fix the issues.

**Comment by 18445864529** [comment]
Worked fine now, thanks.
