### ISSUE TITLE
mt5 small generating wrong predictions

### ISSUE THREAD

**Issue by ashokurlana** [csebuetnlp/xl-sum#8]
I am trying to finetune the mt5-small with Telugu corpus, all the generated summaries includes <extra_id_0> tokens, please suggest how to fixt it.

Example generated output:

<extra_id_0> హోమియోపతి కళాశాలను న్యూఢిల్లీ సెంట్రల్ కౌన్సిల్ ఆఫ్ ప్రత్యేక బృందం బుధవారం పరిశీలించింది.

How to avoid this <extra_id_0> token in the summary? see this [issue](https://github.com/huggingface/transformers/issues/9792) for better understanding

**Comment by abhik1505040** [comment]
Hi, are you using the scripts provided in our repository for fine-tuning and inference? If not, please provide a reference to the code.

**Comment by ashokurlana** [comment]
Yes, I am using the scripts provided in this repository.

**Comment by Tahmid04** [comment]
Hi, this issue is pertinent to the small variant of the mT5 model, not because of any errors in our code. mT5-base or other multilingual models does not exhibit the generation of any special token.
